In [150]:
import numpy as np

# creating a array with 15 elements starting form 0

a = np.arange(15).reshape(5,3)

# Dimensions of a matrix can be found using .ndim container, Number of dimensions gives the rank of the array

a.ndim


2

In [16]:
# type of the matrix helps identify whether it is ndarray in numpy or not

type(a)

numpy.ndarray

In [31]:
#to find the size or number of elements in a array we can use .size container

a.size

15

In [32]:
#to display a ndmatirix pass the variable name

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
# slicing a array to get row, column and element

# get 2nd column

a[:,1]

array([ 1,  6, 11])

In [34]:
# get first row from the ndmatrix

a[1,:]

array([5, 6, 7, 8, 9])

In [36]:
# to target a element from a array we can use 

a[1,1]

6

In [ ]:
#combining the elements usnig the axis method

a.sum(axis =0)



In [41]:
# summation of element using the axis method

a.sum(axis = 1)

array([10, 35, 60])

In [43]:
#create  arrays from list
 
l = [x for x in range(20)]

b = np.array(l)

b


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
# Checking which verison of numpy we are using
#1. Import numpy as np and see the version

print(np.__version__)

1.17.2


In [48]:
#How to create a 1D array?

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# 3. How to create a boolean array?

boolarr = np.full((3, 3), True, dtype=bool)

boolarr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [54]:
#4. How to extract items that satisfy a given condition from 1D array?

ex = np.array([x for x in range(20)])

ex[ex % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [62]:
#5. How to replace items that satisfy a condition with another value in numpy array?

re = np.array([x for x in range(30)])

re[ re % 2 == 1] = -1
re 

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1, 20, -1, 22, -1, 24, -1, 26, -1, 28, -1])

In [81]:
#6 . How to replace items that satisfy a condition without affecting the original array?

newarr = np.arange(30)

out = np.where(newarr % 2 == 1, -1, newarr)

newarr.reshape(-1, 2)


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [89]:
# 8. How to stack two arrays vertically?

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)


# Method 1:
np.concatenate([a, b], axis=0)

# # Method 2:
# np.vstack([a, b])

# # Method 3:
# np.r_[a, b]

# #> array([[0, 1, 2, 3, 4],
# #>        [5, 6, 7, 8, 9],
# #>        [1, 1, 1, 1, 1],
# #>        [1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [92]:
# 9. How to stack two arrays horizontally?

# np.hstack([a,b])

np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [96]:
# 11. How to get the common items between two python numpy arrays?

np.intersect1d(a,b)

array([1])

In [97]:
# 12. How to remove from one array those items that exist in another?

np.setdiff1d(a,b)

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
# 13. How to get the positions where elements of two arrays match?

np.where(a == b)

(array([0]), array([1]))

In [108]:
# 14. How to extract all numbers between a given range from a numpy array?
d = np.arange(20).reshape(4,5)
d


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [111]:
index = np.where( (d >= 5) & (d <= 20))

d[index]

d[(d >= 5) & (d <= 10)]


array([ 5,  6,  7,  8,  9, 10])

In [124]:
np.r_[np.repeat(a, 1)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [127]:
sm = np.arange(9).reshape(3,3)
sm

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [140]:
#Swapping rows in a matix
sm[[1,0,1],:]

array([[3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [ ]:
# How to reverse columns of matrix

sm[:,::-1]

In [152]:
# print the reverse of the elements
sm[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [172]:
# Create a array from elements ranging from 5 to 10


rand_arr = np.dtype(int)
rand_arr = np.random.uniform(5,10, size=(5,3))



array([[ 8.,  7.,  9.],
       [ 6., 10.,  7.],
       [ 7.,  6.,  7.],
       [10.,  8.,  9.],
       [10., 10.,  6.]])

In [180]:
# Celing of the values int the floating array
rand_arr
# rand_arr.astype(int)
np.ceil(rand_arr)
# rand_arr.astype(int)

array([[ 8.,  7.,  9.],
       [ 6., 10.,  7.],
       [ 7.,  6.,  7.],
       [10.,  8.,  9.],
       [10., 10.,  6.]])

In [184]:
len(rand_arr)

5