In [30]:
import numpy as np

# creating a array with 15 elements starting form 0

a = np.arange(15).reshape(3,5)

# Dimensions of a matrix can be found using .ndim container

a.ndim


2

In [16]:
# type of the matrix helps identify whether it is ndarray in numpy or not

type(a)

numpy.ndarray

In [31]:
#to find the size or number of elements in a array we can use .size container

a.size

15

In [32]:
#to display a ndmatirix pass the variable name

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
# slicing a array to get row, column and element

# get 2nd column

a[:,1]

array([ 1,  6, 11])

In [34]:
# get first row from the ndmatrix

a[1,:]

array([5, 6, 7, 8, 9])

In [36]:
# to target a element from a array we can use 

a[1,1]

6

In [ ]:
#combining the elements usnig the axis method

a.sum(axis =0)



In [41]:
# summation of element using the axis method

a.sum(axis = 1)

array([10, 35, 60])

In [ ]:
#create a arrays from list
 
l = [x for x in range(20)]

np.array(l)
