In [30]:
import numpy as np

# creating a array with 15 elements starting form 0

a = np.arange(15).reshape(3,5)

# Dimensions of a matrix can be found using .ndim container, Number of dimensions gives the rank of the array

a.ndim


2

In [16]:
# type of the matrix helps identify whether it is ndarray in numpy or not

type(a)

numpy.ndarray

In [31]:
#to find the size or number of elements in a array we can use .size container

a.size

15

In [32]:
#to display a ndmatirix pass the variable name

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
# slicing a array to get row, column and element

# get 2nd column

a[:,1]

array([ 1,  6, 11])

In [34]:
# get first row from the ndmatrix

a[1,:]

array([5, 6, 7, 8, 9])

In [36]:
# to target a element from a array we can use 

a[1,1]

6

In [ ]:
#combining the elements usnig the axis method

a.sum(axis =0)



In [41]:
# summation of element using the axis method

a.sum(axis = 1)

array([10, 35, 60])

In [43]:
#create  arrays from list
 
l = [x for x in range(20)]

b = np.array(l)

b


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
# Checking which verison of numpy we are using
#1. Import numpy as np and see the version

print(np.__version__)

1.17.2


In [48]:
#How to create a 1D array?

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# 3. How to create a boolean array?

boolarr = np.full((3, 3), True, dtype=bool)

boolarr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [54]:
#4. How to extract items that satisfy a given condition from 1D array?

ex = np.array([x for x in range(20)])

ex[ex % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [62]:
#5. How to replace items that satisfy a condition with another value in numpy array?

re = np.array([x for x in range(30)])

re[ re % 2 == 1] = -1
re 

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1, 20, -1, 22, -1, 24, -1, 26, -1, 28, -1])

In [67]:
#6 . How to replace items that satisfy a condition without affecting the original array?

newarr = np.arange(30)

out = np.where(arr % 2 == 1, -1, arr)

out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])